[package]
name = "inator"
authors = ["Will Sturgeon <willstrgn@gmail.com>"]
version = "0.1.0"
edition = "2021"
description = "Fast declarative zero-copy parsers via nondeterministic finite automata."
license = "MPL-2.0"
repository = "github.com/wrsturgeon/inator"
build = "build.rs"

[dependencies]
proc-macro2 = "1.0.67"
syn = { version = "2.0.34", features = ["full"] }

# Optional dependencies:
quickcheck = { version = "1.0.3", optional = true }
rand = "0.8.5"

[features]
quickcheck = ["dep:quickcheck"]
