[package]
name = "inator-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
inator-automata = { path = "../automata" }
proc-macro2 = "1.0.67"
# quote = "1.0.33"
syn = { version = "2.0.34", features = ["full"] }
